# Generated by Django 5.2.4 on 2025-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
            ],
        ),
    ]
