# Generated by Django 5.2.4 on 2025-07-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_companytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytask',
            name='task_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
