# Generated by Django 5.2.4 on 2025-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_companytask_date_companytask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytask',
            name='task_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
