# Generated by Django 5.2.4 on 2025-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='question',
            field=models.CharField(default='No Question', max_length=100),
            preserve_default=False,
        ),
    ]
